; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:leonardo]
platform = atmelavr
board = leonardo
framework = arduino
build_src_filter = +<main.cpp>

[env:printer_test]
platform = atmelavr
board = leonardo
framework = arduino
build_src_filter = +<printer_test.cpp>

[env:bitmap_test]
platform = atmelavr
board = leonardo
framework = arduino
build_src_filter = +<bitmap_test.cpp>

[env:xiao_printer_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_src_filter = +<xiao_printer_test.cpp>

[env:xiao_bitmap_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_src_filter = +<xiao_bitmap_test.cpp>

[env:xiao_main]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_src_filter = +<xiao_main.cpp>
